components:
  schemas:
    Log:
      additionalProperties: false
      properties:
        code:
          type: string
        payload:
          additionalProperties: false
          type: object
        system_name:
          type: string
        system_version:
          type: number
        timestamp:
          type: integer
      required:
        - timestamp
        - system_name
        - system_version
        - code
        - payload
      title: Log
      type: object
      x-examples:
        '1':
          code: pipeline_success
          payload:
            message: pipeline successfully created
          system_name: user_manager
          system_version: 2
          timestamp: 1583934547
          user_id: 4ae0359e57bf4465b79d730d27f84426
  securitySchemes:
    Authorization:
      description: ''
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: security.check_token
info:
  description: Log manager for the Utelly API platform
  title: audit_manager
  version: v1
openapi: 3.0.0
paths:
  /log:
    post:
      description: Add a Log entry
      operationId: v1.log.post_log
      requestBody:
        content:
          application/json:
            examples:
              '1':
                value:
                  code: pipeline_success
                  payload:
                    message: pipeline successfully created
                  system_name: user_manager
                  system_version: 2
                  timestamp: 1583934547
                  user_id: 4ae0359e57bf4465b79d730d27f84426
            schema:
              $ref: '#/components/schemas/Log'
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    log:
                      code: pipeline_success
                      payload:
                        message: pipeline successfully created
                      system_name: user_manager
                      system_version: 2
                      timestamp: 1583934547
                      user_id: 4ae0359e57bf4465b79d730d27f84426
              schema:
                additionalProperties: false
                type: object
                properties:
                  log:
                    $ref: '#/components/schemas/Log'
                required:
                  - log
          description: OK
      security:
        - Authorization: []
      summary: Add a Log entry
      tags:
        - Audit Management
  /logs:
    parameters: []
    post:
      description: Batch add Log entries
      operationId: v1.logs.post_logs
      parameters: []
      requestBody:
        content:
          application/json:
            examples:
              '1':
                value:
                  - code: pipeline_success
                    payload:
                      message: pipeline successfully created
                    system_name: user_manager
                    system_version: 2
                    timestamp: 1583934547
                    user_id: 4ae0359e57bf4465b79d730d27f84426
            schema:
              type: array
              uniqueItems: false
              items:
                $ref: '#/components/schemas/Log'
        description: ''
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    logs:
                      - code: pipeline_success
                        payload:
                          message: pipeline successfully created
                        system_name: user_manager
                        system_version: 2
                        timestamp: 1583934547
                        user_id: 4ae0359e57bf4465b79d730d27f84426
              schema:
                additionalProperties: false
                type: object
                properties:
                  logs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Log'
                required:
                  - logs
          description: OK
      security:
        - Authorization: []
      summary: Batch add Log entries
      tags:
        - Audit Management
servers:
  - description: prod
    url: 'https://services.utelly.com/audit_manager/v1'
  - description: staging
    url: 'https://staging-services.utelly.com/audit_manager/v1'
  - description: dev
    url: 'https://dev-services.utelly.com/audit_manager/v1'
