components:
  schemas:
    consumer:
      description: ''
      type: object
      x-examples:
        example-1:
          guid: string
          identifiers:
            - id: string
              source: string
          updated_at: string
          created_at: string
          last_n_interactions:
            - type: string
              entity:
                id: string
                source: string
                type: string
          affinities:
            services:
              - guid: string
                score: 0
            genres:
              - guid: string
                score: 0
            tags:
              - guid: string
                score: 0
            people:
              - guid: string
                score: 0
          subscriptions:
            services:
              - guid: string
                datetime_from: '2019-08-24T14:15:22Z'
                datetime_to: '2019-08-24T14:15:22Z'
          currently_watching: string
          kvs: {}
      properties:
        _links:
          type: object
          properties:
            affinities:
              $ref: ../models/hal_link_field.v1.yaml
            lists:
              $ref: ../models/hal_link_field.v1.yaml
            subscriptions:
              $ref: ../models/hal_link_field.v1.yaml
          readOnly: true
        guid:
          type: string
          minLength: 1
          readOnly: true
        identifiers:
          type: array
          items:
            $ref: '#/components/schemas/indentifier'
        updated_at:
          type: string
          readOnly: true
        created_at:
          type: string
          readOnly: true
        last_n_interactions:
          type: array
          items:
            $ref: '#/components/schemas/interaction'
        affinities:
          type: object
          properties:
            services:
              type: array
              items:
                $ref: '#/components/schemas/affinity'
            genres:
              type: array
              items:
                $ref: '#/components/schemas/affinity'
            tags:
              type: array
              items:
                $ref: '#/components/schemas/affinity'
            people:
              type: array
              items:
                $ref: '#/components/schemas/affinity'
        subscriptions:
          type: object
          properties:
            services:
              type: array
              items:
                $ref: '#/components/schemas/subscription'
        currently_watching:
          type: string
        kvs:
          type: object
    subscription:
      description: ''
      type: object
      x-examples:
        example-1:
          _links:
            service:
              href: string
          guid: string
          datetime_from: '2019-08-24T14:15:22Z'
          datetime_to: '2019-08-24T14:15:22Z'
      properties:
        _links:
          type: object
          properties:
            service:
              $ref: ../models/hal_link_field.v1.yaml
            location:
              $ref: ../models/hal_link_field.v1.yaml
            consumer:
              $ref: ../models/hal_link_field.v1.yaml
          readOnly: true
        guid:
          type: string
          minLength: 1
          readOnly: true
        datetime_from:
          type: string
          format: date-time
        datetime_to:
          type: string
          format: date-time
        service_guid:
          type: string
          writeOnly: true
        location_guid:
          type: string
          writeOnly: true
      required:
        - _links
        - guid
        - datetime_from
        - service_guid
        - location_guid
    affinity:
      description: ''
      type: object
      x-examples:
        example-1:
          _links:
            creative_work:
              href: string
          guid: string
          score: 0
          type: manual
      properties:
        _links:
          oneOf:
            - behavior: Read Only
              properties:
                tag:
                  $ref: ../models/hal_link_field.v1.yaml
                consumer:
                  $ref: ../models/hal_link_field.v1.yaml
            - properties:
                person:
                  $ref: ../models/hal_link_field.v1.yaml
                consumer:
                  $ref: ../models/hal_link_field.v1.yaml
              behavior: Read Only
            - properties:
                service:
                  $ref: ../models/hal_link_field.v1.yaml
                consumer:
                  $ref: ../models/hal_link_field.v1.yaml
              behavior: Read Only
          type: object
        guid:
          type: string
          readOnly: true
        score:
          type: number
        type:
          type: string
          enum:
            - manual
            - auto
        tag:
          type: string
          description: tag guid
          writeOnly: true
        person:
          type: string
          description: person guid
          writeOnly: true
        service:
          type: string
          description: service guid
          writeOnly: true
      required:
        - guid
        - score
        - type
    interaction:
      description: ''
      type: object
      properties:
        type:
          type: string
        entity:
          type: object
          properties:
            id:
              type: string
            source:
              type: string
            type:
              type: string
          required:
            - id
            - source
            - type
      required:
        - type
        - entity
      x-examples:
        example-1:
          type: ''
          entity:
            id: ''
            source: ''
            type: ''
    indentifier:
      description: ''
      type: object
      properties:
        id:
          type: string
        source:
          type: string
      required:
        - id
        - source
      x-examples:
        example-1:
          id: ''
          source: ''
    filters:
      title: filters
      type: array
      items: {}
    filter:
      title: filter
      type: object
      properties:
        property:
          type: string
        operator:
          type: string
        value:
          anyOf:
            - items:
                type: string
          type:
            - array
            - string
      required:
        - property
        - operator
        - value
    list:
      title: list
      type: object
      properties:
        _links:
          type: object
          properties:
            creative_works:
              $ref: ../models/hal_link_field.v1.yaml
            consumer:
              $ref: ../models/hal_link_field.v1.yaml
          readOnly: true
        guid:
          type: string
          readOnly: true
        type:
          type: string
          enum:
            - continue_watching
            - watchlist
        created_at:
          type: string
          readOnly: true
        updated_at:
          type: string
          readOnly: true
        name:
          type: string
        creative_works:
          type: array
          description: creative work guids
          items:
            type: string
            writeOnly: true
          writeOnly: true
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: security.check_token
  parameters: {}
  requestBodies:
    consumer:
      content:
        application/json:
          schema:
            type: object
            properties:
              consumer:
                $ref: '#/components/schemas/consumer'
        application/xml:
          schema:
            type: object
            properties: {}
        multipart/form-data:
          schema:
            type: object
            properties: {}
        text/html:
          schema:
            type: object
            properties: {}
        text/plain:
          schema:
            type: object
            properties: {}
    subscription:
      content:
        application/json:
          schema:
            type: object
            properties:
              subscription:
                $ref: '#/components/schemas/subscription'
    affinity:
      content:
        application/json:
          schema:
            type: object
            properties:
              affinity:
                $ref: '#/components/schemas/affinity'
    list:
      content:
        application/json:
          schema:
            type: object
            properties:
              list:
                $ref: '#/components/schemas/list'
  responses:
    consumer:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/consumer'
    subscription:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/subscription'
    list:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/list'
    affinity:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/affinity'
info:
  contact:
    email: developers@utelly.com
    name: API Support
  description: ''
  title: consumer_manager
  version: v1
openapi: 3.0.0
paths:
  '/consumers/{consumer_guid}':
    get:
      summary: Get a Consumer
      tags:
        - Consumer Management
      responses:
        '200':
          $ref: '#/components/responses/consumer'
      operationId: get-consumers
      description: ''
    parameters:
      - schema:
          type: string
        name: consumer_guid
        in: path
        required: true
    post:
      summary: Update Consumer
      operationId: post-consumers-consumer_guid
      requestBody:
        $ref: '#/components/requestBodies/consumer'
      responses:
        '200':
          $ref: '#/components/responses/consumer'
      tags:
        - Consumer Management
  /consumers:
    get:
      summary: List Consumers
      tags:
        - Consumer Management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _embedded:
                    type:
                      - string
                      - object
                    properties:
                      consumers:
                        type: array
                        items:
                          $ref: '#/components/schemas/consumer'
                  _links:
                    $ref: ../models/HalLinks.v1.yaml
      operationId: get-consumers
      parameters:
        - schema:
            type: string
          in: query
          name: filters
          description: json value of the Filters object
        - schema:
            type: string
          in: query
          name: after_guid
        - schema:
            type: string
          in: query
          name: before_guid
        - schema:
            type: string
          in: query
          name: before_or_eq_guid
        - schema:
            type: string
          in: query
          name: fields
        - schema:
            type: string
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: skip
        - schema:
            type: string
          in: query
          name: sort
    post:
      summary: Create Consumer
      operationId: post-consumers
      responses:
        '200':
          $ref: '#/components/responses/consumer'
      description: ''
      requestBody:
        $ref: '#/components/requestBodies/consumer'
      tags:
        - Consumer Management
  '/consumers/{consumer_guid}/affinities':
    parameters:
      - schema:
          type: string
        name: consumer_guid
        in: path
        required: true
    get:
      summary: List Consumer Affinities
      tags:
        - Affinities Management
      responses: {}
      operationId: get-consumers-consumer_guid-affinities
      parameters:
        - schema:
            type: string
          in: query
          name: filters
          description: json value of the Filters object
        - schema:
            type: string
          in: query
          name: after_guid
        - schema:
            type: string
          in: query
          name: before_guid
        - schema:
            type: string
          in: query
          name: before_or_eq_guid
        - schema:
            type: string
          in: query
          name: fields
        - schema:
            type: string
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: skip
        - schema:
            type: string
          in: query
          name: sort
    post:
      summary: Create User Affinity
      operationId: post-consumers-consumer_guid-affinities
      responses:
        '200':
          $ref: '#/components/responses/affinity'
      requestBody:
        $ref: '#/components/requestBodies/affinity'
      tags:
        - Affinities Management
  '/consumers/{consumer_guid}/lists':
    parameters:
      - schema:
          type: string
        name: consumer_guid
        in: path
        required: true
    get:
      summary: List Consumer Lists
      tags:
        - Lists Management
      responses: {}
      operationId: get-consumers-consumer_guid-continue_watching
      description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: filters
          description: json value of the Filters object
        - schema:
            type: string
          in: query
          name: after_guid
        - schema:
            type: string
          in: query
          name: before_guid
        - schema:
            type: string
          in: query
          name: before_or_eq_guid
        - schema:
            type: string
          in: query
          name: fields
        - schema:
            type: string
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: skip
        - schema:
            type: string
          in: query
          name: sort
    post:
      summary: Create Consumer List
      operationId: post-consumers-consumer_guid-lists
      responses:
        '200':
          $ref: '#/components/responses/list'
      requestBody:
        $ref: '#/components/requestBodies/list'
      tags:
        - Lists Management
  '/consumers/{consumer_guid}/subscriptions':
    parameters:
      - schema:
          type: string
        name: consumer_guid
        in: path
        required: true
    get:
      summary: List Consumer Subscriptions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _embedded:
                    type:
                      - string
                      - object
                    properties:
                      subscriptions:
                        type: array
                        items:
                          $ref: '#/components/schemas/subscription'
                  _links:
                    $ref: ../models/HalLinks.v1.yaml
      operationId: get-consumers-consumer_guid-subscriptions
      tags:
        - Subscriptions Management
      parameters:
        - schema:
            type: string
          in: query
          name: filters
          description: json value of the Filters object
        - schema:
            type: string
          in: query
          name: after_guid
        - schema:
            type: string
          in: query
          name: before_guid
        - schema:
            type: string
          in: query
          name: before_or_eq_guid
        - schema:
            type: string
          in: query
          name: fields
        - schema:
            type: string
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: skip
        - schema:
            type: string
          in: query
          name: sort
    post:
      summary: Create Subscription
      operationId: post-consumers-consumer_guid-subscriptions
      responses:
        '200':
          $ref: '#/components/responses/subscription'
      requestBody:
        $ref: '#/components/requestBodies/subscription'
      tags:
        - Subscriptions Management
  '/subscriptions/{subscription_guid}':
    parameters:
      - schema:
          type: string
        name: subscription_guid
        in: path
        required: true
    get:
      summary: Get Subscription
      responses:
        '200':
          $ref: '#/components/responses/subscription'
      operationId: get-subscriptions-subscription_guid
      description: ''
      tags:
        - Subscriptions Management
    put:
      summary: Update Subscription
      operationId: put-subscriptions-subscription_guid
      responses:
        '200':
          $ref: '#/components/responses/subscription'
      requestBody:
        $ref: '#/components/requestBodies/subscription'
      tags:
        - Subscriptions Management
  '/lists/{list_guid}':
    parameters:
      - schema:
          type: string
        name: list_guid
        in: path
        required: true
    get:
      summary: Get List
      tags:
        - Lists Management
      responses:
        '200':
          $ref: '#/components/responses/list'
      operationId: get-list-list_guid
    put:
      summary: Update List
      operationId: put-list-list_guid
      responses:
        '200':
          $ref: '#/components/responses/list'
      requestBody:
        $ref: '#/components/requestBodies/list'
      tags:
        - Lists Management
  '/affinities/{affinity_guid}':
    parameters:
      - schema:
          type: string
        name: affinity_guid
        in: path
        required: true
    get:
      summary: Get Affinity
      tags:
        - Affinities Management
      responses:
        '200':
          $ref: '#/components/responses/affinity'
      operationId: get-affinities-affinity_guid
    put:
      summary: Update Affinity
      operationId: put-affinities-affinity_guid
      responses:
        '200':
          $ref: '#/components/responses/affinity'
      requestBody:
        $ref: '#/components/requestBodies/affinity'
      tags:
        - Affinities Management
servers:
  - description: prod
    url: 'https://services.utelly.com/consumer_manager/v1'
  - description: staging
    url: 'https://staging-services.utelly.com/consumer_manager/v1'
  - description: dev
    url: 'https://dev-services.utelly.com/consumer_manager/v1'
tags:
  - name: utelly_services
