openapi: 3.0.0
info:
  title: Content Searching
  version: '1.0'
  description: The following API is responsible for content searching
servers:
  - url: 'https://api.utelly.com/phoenix/9'
paths:
  /lookup:
    get:
      summary: lookup
      tags: []
      operationId: get-lookup
      description: An object with response attributes for the combination of term / location
      parameters:
        - schema:
            type: string
          in: query
          name: term
          description: The term to perform search upon
          required: true
        - schema:
            type: string
          in: header
          name: X-AppKey
          description: Key providing access to the api
          required: true
        - schema:
            type: string
          in: query
          name: country
          description: Location to get search results from - Defaults to UK if not specified
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items: {}
                  updated:
                    type: string
                  term:
                    type: string
                  status_code:
                    type: string
                  variant:
                    type: string
components:
  schemas: {}
  securitySchemes: {}
