openapi: 3.0.0
info:
  title: Content Searching
  version: '1.0'
  description: The following API is responsible for content searching
servers:
  - url: 'https://api.utelly.com/phoenix/9'
paths: {}
components:
  schemas: {}
  securitySchemes: {}
