info:
  description: ''
  title: discover_manager
  version: v1
openapi: 3.0.0
paths:
  /creative_works/discover:
    get:
      description: ''
      operationId: v1.discover.creative_work.get
      parameters:
        - explode: true
          in: query
          name: channels
          schema:
            items:
              type: string
            type: array
          style: pipeDelimited
        - explode: true
          in: query
          name: release_years
          schema:
            items:
              type: integer
            type: array
          style: pipeDelimited
        - explode: true
          in: query
          name: content_ratings
          schema:
            items:
              type: string
            type: array
          style: pipeDelimited
        - explode: true
          in: query
          name: genres
          schema:
            items:
              type: string
            type: array
          style: pipeDelimited
        - explode: true
          in: query
          name: types
          schema:
            items:
              type: string
            type: array
          style: pipeDelimited
        - explode: true
          in: query
          name: guids
          schema:
            items:
              type: string
            type: array
          style: pipeDelimited
        - explode: true
          in: query
          name: titles
          schema:
            items:
              type: string
            type: array
          style: pipeDelimited
        - in: query
          name: order_by
          schema:
            enum:
              - popularity
              - relevancy
              - release_year
              - recommendation
              - rating
            type: string
        - in: query
          name: refresh_rate
          schema:
            type: integer
        - explode: true
          in: query
          name: title_shuffle_set
          schema:
            items:
              type: integer
            type: array
          style: pipeDelimited
        - in: query
          name: shuffle_rate
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            maximum: 50
            minimum: 0
            type: integer
        - explode: true
          in: query
          name: durations
          schema:
            items:
              $ref: ../models/integer_range_field.v1.yaml
            type: array
          style: pipeDelimited
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    _embedded:
                      creative_works:
                        - _links:
                            availabilities:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/availabilities
                            content_ratings:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/content_ratings
                            contributors:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/contributors
                            episodes:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/episodes
                            seasons:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/seasons
                            self:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46
                            tags:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/tags
                          artworks:
                            - height: 100
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: poster
                              url: 'https://mydomain.com/poster.jpg'
                              width: 100
                          created_at: '2020-01-01T00:00:10Z'
                          deleted: false
                          descriptions:
                            - description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.'
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: full
                          guid: 27c13eec19014084a0a3173061702b46
                          identifiers:
                            - id: '1'
                              source: mysource
                          relationships:
                            - href: /content/creative_works/eac7cb1192264b088ccbad0874395ce5
                              rel: parent
                          titles:
                            - metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: official
                              title: The Usual Suspects
                          type: movie
                          updated_at: '2020-01-01T00:00:10Z'
                    _links:
                      first:
                        href: /content/creative_works
                      last:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                      next:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                      prev:
                        href: /content/creative_works
                      self:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
              schema:
                additionalProperties: false
                properties:
                  _embedded:
                    additionalProperties: false
                    properties:
                      creative_works:
                        items:
                          $ref: ./browse_manager.v1.yaml#/components/schemas/CreativeWork
                        type: array
                    type: object
                  _links:
                    $ref: ../models/HalLinks.v1.yaml
                required:
                  - _embedded
                  - _links
                type: object
          description: OK
      summary: Discover Creative Works
      tags: []
  /pages:
    get:
      summary: List pages
      tags:
        - Discovery Pages
      responses: {}
      operationId: get-pages
      description: ''
  '/pages/{page_slug}':
    get:
      summary: Get a page
      tags:
        - Discovery Pages
      responses: {}
      operationId: get-pages
      description: ''
    parameters:
      - schema:
          type: string
        name: page_slug
        in: path
        required: true
  '/pages/{page_slug}/collections':
    parameters:
      - schema:
          type: string
        name: page_slug
        in: path
        required: true
    get:
      summary: Get collections from a page
      responses: {}
      operationId: get-pages-page_slug-collections
      tags:
        - Discovery Collections
  /collections:
    get:
      summary: List collections
      tags:
        - Discovery Collections
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _links:
                    $ref: ../models/HalLinks.v1.yaml
                  _embedded:
                    type: object
                    properties:
                      collections:
                        type: array
                        items:
                          $ref: '#/components/schemas/Collection'
      operationId: get-collections
      description: ''
  '/collections/{collection_guid}':
    parameters:
      - schema:
          type: string
        name: collection_guid
        in: path
        required: true
    get:
      summary: Get a collection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'
      operationId: get-collections-collection_guid
      tags:
        - Discovery Collections
  '/collections/{collection_guid}/creative_works':
    parameters:
      - schema:
          type: string
        name: collection_guid
        in: path
        required: true
    get:
      summary: Get creative works from a collection
      tags: []
      responses: {}
      operationId: get-collections-collection_guid-creative_works
      description: ''
servers:
  - description: prod
    url: 'https://services.utelly.com/discover_manager/v1'
  - description: staging
    url: 'https://staging-services.utelly.com/discover_manager/v1'
  - description: dev
    url: 'https://dev-services.utelly.com/discover_manager/v1'
components:
  schemas:
    Page:
      description: A page is a grouping of collections. Indended to be rendered as a single view in an application.
      type: object
      x-examples:
        example-1:
          _links:
            collections:
              href: '/discover_manager/v1/page/{page_slug}/collections'
            self:
              href: '/discover_manager/v1/page/{page_slug}'
          names:
            - name: Home Page
              metadata:
                type: ''
                language: en
                country: GB
          descriptions:
            - description: Discover great content
              metadata:
                type: ''
                language: en
                country: GB
          artworks: []
          version: ''
          slug: page_slug
      title: Page
      properties:
        _links:
          type: object
          required:
            - collections
            - self
          properties:
            collections:
              $ref: ../models/hal_link_field.v1.yaml
            self:
              $ref: ../models/hal_link_field.v1.yaml
        names:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              name:
                type: string
                minLength: 1
              metadata:
                $ref: ./browse_manager.v1.yaml#/components/schemas/metadata_field
            required:
              - name
        descriptions:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              description:
                type: string
                minLength: 1
              metadata:
                $ref: ./browse_manager.v1.yaml#/components/schemas/metadata_field
            required:
              - description
        artworks:
          $ref: ./browse_manager.v1.yaml#/components/schemas/picture_field
        version:
          type: string
        slug:
          type: string
          minLength: 1
      required:
        - _links
        - names
        - descriptions
        - artworks
        - version
        - slug
    Collection:
      description: 'A collection is a grouping of content for browsing based discovery '
      type: object
      x-examples: {}
      properties:
        _links:
          type: object
          required:
            - creative_works
            - self
          properties:
            creative_works:
              $ref: ../models/hal_link_field.v1.yaml
            self:
              $ref: ../models/hal_link_field.v1.yaml
        names:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              name:
                type: string
                minLength: 1
              metadata:
                $ref: ./browse_manager.v1.yaml#/components/schemas/metadata_field
            required:
              - name
        descriptions:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              description:
                type: string
                minLength: 1
              metadata:
                $ref: ./browse_manager.v1.yaml#/components/schemas/metadata_field
            required:
              - description
        hero:
          type: string
        guid:
          type: string
      required:
        - _links
        - names
        - descriptions
        - hero
      title: Collection
