components:
  schemas: {}
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: security.check_token
info:
  contact:
    email: developers@utelly.com
    name: API Support
  title: email_manager
  version: v1
openapi: 3.0.0
paths:
  /send_email:
    post:
      description: ''
      operationId: v1.email.send
      requestBody:
        content:
          application/json:
            examples:
              '1':
                value:
                  email_body: Hey {name} !, here is your {token}
                  email_from: hello@email.com
                  email_to: keizer@email.com
                  subject: Hey! Looks like you forgot your password
                  variables:
                  - key: name
                    value: Keizer
                  - key: token
                    value: token
            schema:
              additionalProperties: false
              properties:
                email_body:
                  type: string
                email_from:
                  type: string
                email_to:
                  type: string
                subject:
                  type: string
                variables:
                  items:
                    $ref: ../models/kv_field.v1.yaml
                  type: array
              required:
              - variables
              - email_body
              - email_to
              - subject
              type: object
        description: ''
      responses:
        '200':
          description: OK
      security:
      - Authorization: []
      summary: Send email
      tags:
      - Email Management
servers:
- description: prod
  url: https://services.utelly.com/email_manager/v1
- description: staging
  url: https://staging-services.utelly.com/email_manager/v1
- description: dev
  url: https://dev-services.utelly.com/email_manager/v1
tags:
- name: utelly_services
