additionalProperties: false
title: Environment
type: object
x-examples:
  '1':
    description:
      - locale: en
        value: use and make things to break them
    id: 1
    name:
      - locale: en
        value: development
      - locale: nl
        value: ontwikkeling
    tooltip:
      - locale: en
        value: this environment gets refreshed daily
x-tags:
  - Models
properties:
  uid:
    type: string
  names:
    type: object
  descriptions:
    type: string
required:
  - uid
  - names
